#!/usr/bin/perl
#
# generate_template.pl - part of fetchconfig
# Copyright (c) 2026 Rainer Tammer
#
# fetchconfig is free software; see the GNU General Public License v2+.
#
# generate_template.pl - scaffold a generic-model template (see
# README.generic-model) from a session captured with record-session.pl.
#
# It reads the .hex file (the byte-accurate record of a real login + show +
# logout), reconstructs the device (<) and input (>) streams in order, and
# proposes a template: the transport-specific login sequence, the learned
# prompt, the show command, and the capture boundaries. It CANNOT know the
# judgment calls a single capture does not reveal (which lines are volatile,
# whether a pager command is needed, menu handling), so it marks those with
# "# TODO" for a human to complete.
#
# THE OUTPUT IS A DRAFT, NOT A FINISHED TEMPLATE. Review it, run it against
# the device with the generic model, and adjust. See README.generic-model.
#
# Usage:
#   generate_template.pl -f SESSION.hex [-t ssh|telnet] [-o OUT.tmpl]
#
#   -f, --hex FILE       the .hex capture from record-session.pl (required)
#   -t, --transport T    ssh or telnet (default: guessed from the capture)
#   -o, --output FILE    write the template here (default: stdout)
#       --help
#
# No non-core modules.
#

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case bundling);

my $VERSION = '9.63';
my (%opt, $show_help);
GetOptions(
    'f|hex=s'       => \$opt{hex},
    't|transport=s' => \$opt{transport},
    'o|output=s'    => \$opt{output},
    'help'          => \$show_help,
) or usage(2);
usage(0) if $show_help;
usage(2) unless defined $opt{hex};

# --- read the .hex and reconstruct the two streams -------------------------
open(my $fh, '<', $opt{hex}) or die "cannot read $opt{hex}: $!\n";
my @chunks;                 # ordered [dir, bytes]
my ($cur_dir, $cur) = (undef, '');
while (my $line = <$fh>) {
    if ($line =~ /^([<>])\s+0x([0-9a-f]+):\s+((?:[0-9a-f]{2}\s?)+)/) {
        my ($dir, $off, $hex) = ($1, hex($2), $3);
        my $bytes = join '', map { chr hex } ($hex =~ /([0-9a-f]{2})/g);
        if ($off == 0) {
            push @chunks, [$cur_dir, $cur] if defined $cur_dir;
            ($cur_dir, $cur) = ($dir, $bytes);
        } else {
            $cur .= $bytes;
        }
    }
}
push @chunks, [$cur_dir, $cur] if defined $cur_dir;
close $fh;
die "no session data found in $opt{hex}\n" unless @chunks;

my $dev = join '', map { $_->[0] eq '<' ? $_->[1] : '' } @chunks;
my $inp = join '', map { $_->[0] eq '>' ? $_->[1] : '' } @chunks;

# --- infer the transport ---------------------------------------------------
# telnet capture usually starts with IAC negotiation (0xff) and shows a
# "Username:"/"Password:" login; an SSH capture starts at the prompt.
my $transport = $opt{transport};
if (!defined $transport) {
    $transport = ($dev =~ /\xff/ || $dev =~ /Username:|login:/i) ? 'telnet' : 'ssh';
}

# --- infer the prompt ------------------------------------------------------
# The prompt is the token the device repeats before each command. Look at
# the strings that immediately precede the input the operator typed. The
# most common trailing "<host><tail>" is the prompt.
my $stripped = $dev;
$stripped =~ s/\x1b\[[0-9;?]*[A-Za-z]//g;   # remove CSI escapes for analysis
$stripped =~ s/[\x00-\x08\x0b-\x1f\x7f]//g;

my ($prompt_host, $prompt_tail) = ('', '#');
if ($stripped =~ /(\S+)([>#])\s*$/) { $prompt_host = $1; $prompt_tail = $2; }
my $saw_ansi = ($dev =~ /\x1b\[/) ? 1 : 0;

# --- infer the show command (the longest "show ..." the operator typed) ----
my $show_cmd = 'show running-config';
my @typed = map { s/[\r\n].*//s; $_ } split /(?<=[\r\n])/, $inp;
for my $line ($inp =~ /((?:show|write)[^\r\n]*)/g) {
    $show_cmd = $line if length($line) > length($show_cmd) - 4;   # prefer a real one seen
}

# --- emit the template -----------------------------------------------------
my $out;
if (defined $opt{output}) {
    open($out, '>', $opt{output}) or die "cannot write $opt{output}: $!\n";
} else {
    $out = \*STDOUT;
}

my $entry = "state_login_$transport";
print $out <<"HEADER";
# Generated by generate_template.pl $VERSION from $opt{hex}
# THIS IS A DRAFT - review every line, especially the "# TODO" items, and
# test it against the device with the generic model. See
# README.generic-model.
#
# Inferred: transport=$transport, prompt host="$prompt_host" tail="$prompt_tail",
#           ANSI/VT100 escapes @{[ $saw_ansi ? 'PRESENT' : 'none' ]}.

transport      $transport
banner_timeout 30
fetch_timeout  120
prompt_settle  250
max_visits     8
strip_ansi     @{[ $saw_ansi ? 'yes' : 'no' ]}

prompt_head    @{[ $saw_ansi ? "'(?:\\\\x1b\\\\[[\\\\d;?]*[A-Za-z])*'" : "''" ]}
prompt_tail    '$prompt_tail'

# TODO: add volatile lines to ignore when comparing backups. A single
# capture cannot reveal these - compare two captures taken minutes apart
# and ignore any line that changed on its own (timestamps, re-salted
# hashes). Example:
# ignore  /^! Last configuration change/
#
# ---------------------------------------------------------------------------
# TRIMMING THE TOP OF THE SAVED CONFIG
# The capture includes the echoed command and any preamble the device prints
# before the real config (e.g. "show running-config", "Building
# configuration...", "Running configuration:"). Trim it with:
#
#   first_config_line_starts_with "PREFIX"
#       drop every line before the first one that begins with the literal
#       PREFIX (keeping that line). Self-adjusting; the simplest option.
#   capture_from /regex/     same idea but the start is a regex match.
#   skip_first N             drop exactly the first N lines (fixed count).
#
# The number of lines dropped and the final saved line count are logged.
# For Cisco IOS/IOS-XE the config starts at the first "!" line, matching a
# TFTP export:
first_config_line_starts_with  "!"

HEADER

if ($saw_ansi) {
    print $out <<"INTR";
# TODO: this looks like a menu/VT100 device. Confirm the interrupt screens
# and their keystrokes from the capture, e.g.:
# interrupt /Press any key to continue/ -> send_nolf " "
# interrupt /Do you want to log out \\[y\\/n\\]/ -> send_nolf "y"

INTR
}

# login section
if ($transport eq 'telnet') {
    print $out <<"LOGIN";
$entry
    expect /Username: \$/   -> send user            -> goto state_password_telnet
    expect /Password: \$/   -> send_secret pass      -> goto after_login

state_password_telnet
    expect /Password: \$/   -> send_secret pass      -> goto after_login

# TODO: if this device drops you into a menu instead of the CLI, add a
# bounded branch here to escape it, e.g.:
#     expect /Main Menu/  -> send_nolf "5" -> goto after_login
state after_login
    expect /(\\S+)[>#]\$/   -> send "enable"         -> goto enable_pw
LOGIN
} else {
    print $out <<"LOGIN";
# SSH is already authenticated; match the first prompt and send enable.
$entry
    expect /(\\S+)[>#]\$/   -> send "enable"         -> goto enable_pw
LOGIN
}

print $out <<"BODY";

# response to "enable": a Password: prompt, or (already enabled) the prompt.
state enable_pw
    expect /Password: \$/   -> send_secret enable    -> goto pager
    expect prompt          -> send "term len 0"      -> goto show

# response to the enable password is the prompt; send the pager-off command.
# TODO: confirm the pager command for this device ("term len 0" is Cisco;
# ProCurve uses "no page"; others differ - or remove this state if none).
state pager
    expect prompt          -> send "term len 0"      -> goto show

# send the show command captured from the session
state show
    expect prompt          -> send "$show_cmd" -> goto capture

# capture the configuration (text between the show command and the prompt)
state capture
    capture_start
    expect prompt          -> capture_stop           -> goto logout

# already at the prompt: send exit without waiting
state logout
    send "exit" -> done
BODY

close $out if defined $opt{output};

if (defined $opt{output}) {
    print STDERR "Wrote $opt{output} (a DRAFT - review the TODO items and test it).\n";
}
exit 0;

sub usage {
    my ($rc) = @_;
    print STDERR <<'USAGE';
generate_template.pl - scaffold a generic-model template from a
record-session.pl .hex capture. THE OUTPUT IS A DRAFT to review and test.

  generate_template.pl -f SESSION.hex [-t ssh|telnet] [-o OUT.tmpl]

  -f, --hex FILE       the .hex capture (required)
  -t, --transport T    ssh or telnet (default: guessed from the capture)
  -o, --output FILE    write here (default: stdout)
      --help           this help

See README.generic-model for the template grammar.
USAGE
    exit $rc;
}
